import { AttachFile } from "@mui/icons-material";
import { Box, Card, CardContent, Chip, Typography } from "@mui/material";
import Markdown from "react-markdown";
import { ContentBlock, ImageContentBlock } from "../../models/Message";

const renderImageContentBlock = (imageBlock: ImageContentBlock & { type: 'image' }, classes: any, index: number) => {
    return (
        <Box
            key={index} className={classes.imageContainer}
            component="img"
            src={`data:${imageBlock.mime_type};base64,${imageBlock.base64}`}
            alt="Generated by AI, for illustrative purposes"
            style={{ maxWidth: '100%', height: 'auto', display: 'block' }}
        />
    );
};

const renderFileContentBlock = (fileBlock: ContentBlock & { type: 'file' }, classes: any, index: number) => {
    return (
        <Card key={index} className={classes.fileBlock}>
            <CardContent>
                <Box display="flex" alignItems="center" gap={1}>
                    <AttachFile fontSize="small" />
                    <Chip label={fileBlock.extras?.filename ?? fileBlock.mime_type} size="small" variant="outlined" />
                </Box>
            </CardContent>
        </Card>
    );
};

export const renderMessageContent = (content: string | ContentBlock[], classes: any) => {
    if (typeof content === 'string') {
        return (
            <Typography className={classes.markdownContainer} component="div">
                <Markdown
                    components={{
                        img: ({ node, ...props }) => (
                            <img alt="Generated by AI, for illustrative purposes" {...props} />
                        ),
                    }}
                >
                    {content}
                </Markdown>
            </Typography>
        );
    }
    
    return (
        <Box>
            {content.map((block, index) => {
                if (block.type === 'text') {
                    return (
                        <Typography 
                            key={index} 
                            className={classes.markdownContainer} 
                            component="div"
                            sx={{ mb: index < content.length - 1 ? 2 : 0 }}
                        >
                            <Markdown
                                components={{
                                    img: ({ node, ...props }) => (
                                        <img alt="Generated by AI, for illustrative purposes" {...props} />
                                    ),
                                }}
                            >
                                {block.text}
                            </Markdown>
                        </Typography>
                    );
                } else if (block.type === 'image') {
                    return renderImageContentBlock(block, classes, index);
                } else if (block.type === 'file') {
                    return renderFileContentBlock(block, classes, index);
                }
                return null;
            })}
        </Box>
    );
};