import { Box, Typography } from "@mui/material";
import { makeStyles } from "tss-react/mui";
import Markdown from "react-markdown";

interface StreamedMessageItemProps {
    content: string;
}

const useStyles = makeStyles()((_theme) => ({
    container: {
        display: 'flex',
        justifyContent: 'flex-start',
        flexDirection: "column-reverse",
    },
    markdownContainer: {
        width: '100%',
        wordBreak: 'break-word',
        hyphens: 'auto',
        '& img': {
            width: '100%',
            height: 'auto',
        },
        '& pre, & code': {
            whiteSpace: 'pre-wrap',
            wordBreak: 'break-all',
        },
    },
    cursorBlink: {
        display: 'inline-block',
        width: '2px',
        height: '1em',
        backgroundColor: 'currentColor',
        marginLeft: '2px',
        animation: '$blink 1s step-end infinite',
        verticalAlign: 'middle',
    },
    '@keyframes blink': {
        '0%, 100%': { opacity: 1 },
        '50%': { opacity: 0 },
    },
}));

export const StreamedMessageItem = ({ content }: StreamedMessageItemProps) => {
    const { classes } = useStyles();

    return (
        <Box className={classes.container}>
            <Box marginLeft={1}>
                <Typography className={classes.markdownContainer} component="div">
                    <Markdown
                        components={{
                            img: ({ node, ...props }) => (
                                <img alt="Generated by AI, for illustrative purposes" {...props} />
                            ),
                        }}
                    >
                        {content}
                    </Markdown>
                    <Box component="span" className={classes.cursorBlink} />
                </Typography>
            </Box>
        </Box>
    );
};
